name: release-pr

on:
  pull_request:
    branches: ["main"]

jobs:
  test-and-build:
    uses: ./.github/workflows/test.yml
    if: "startsWith(github.head_ref, 'release/') && !github.event.pull_request.head.fork"
  prepare-release:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    needs: test-and-build
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@stable
    - name: Create Tag
      run: |
        VERSION=$(cargo metadata --format-version=1 --no-deps | jq -r '.packages[0].version')
        TAG="v${VERSION}"
        echo "VERSION=${VERSION} TAG=${TAG}"
        hub release --include-drafts -f "%t:%S%n"
        if hub release --include-drafts -f "%t:%S%n" | grep -x -F "${TAG}:draft" >/dev/null; then
          echo Delete existing release
          gh release delete "${TAG}"
        fi
        if git fetch origin tag "${TAG}" >/dev/null; then
          echo Delete existing tag
          git tag -d "${TAG}"
          git push origin :"${TAG}"
        fi
        gh release create "${TAG}" --title "${TAG}" --draft
